//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkolaMVC.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocjena
    {
        public int OcjenaId { get; set; }
        public int UcenikId { get; set; }
        public System.DateTime Datum { get; set; }
        public int VrijednostOcjene { get; set; }
        public int TipOcjene { get; set; }
        public int PredmetId { get; set; }
        public int NastavnikId { get; set; }
    
        public virtual Nastavnik Nastavnik { get; set; }
        public virtual Predmet Predmet { get; set; }
        public virtual Ucenik Ucenik { get; set; }
    }
}
